version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: "06:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 2
    labels:
      - dependencies
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
    groups:
      github-actions:
        patterns:
          - "*"
